### PR TITLE
don't add empty sfx name to validUrls

### PR DESCRIPTION
**Pull request by headshot2017**
source: adachi char.ini SoundN 50

### CODE REVIEW

**Comment by stonedDiscord** [comment]
maybe the length should be bigger than 1, i haven't seen anyone use a 1character long sfx name

**Comment by Ganty1999** [comment]
maybe try to avoiding the value of sfx name like this.

1. "-"
2. "1" or any int
3. too much space aka _trimmed_

**Comment by headshot2017** [comment]
> maybe try to avoiding the value of sfx name like this.
> 
> 1. "-"
> 2. "1" or any int
> 3. too much space aka _trimmed_

1. it already checks if the length of the name is longer than 1 character
2. see above. it will never be an int. the ini library always parses string values when reading char.ini
3. too much space? you mean like a long name? that doesn't really matter

**Comment by Ganty1999** [comment]
> 3. too much space? you mean like a long name? that doesn't really matter

i mean somehow like this "24=   " in mostly inis files.

**Comment by headshot2017** [comment]
> > 3. too much space? you mean like a long name? that doesn't really matter
> 
> i mean somehow like this "24=   " in mostly inis files.

whether it's written as "24     = sfx" or "24=sfx" doesn't matter, the ini library handles that

**Comment by Ganty1999** [comment]
hopefully the ini library not be bug in future.

anyways, approved this btw, @stonedDiscord

**Pull request merged**
